---
title: "test"
author: "Thomas Curran"
date: "4/21/2017"
output: html_document
---

```{r setup, results='hide',include=FALSE,echo=FALSE, warnings=FALSE, tidy=TRUE}
###preparation file
library(data.table)
library(quanteda)
library(stringr)
library(tidyverse)

load("PRESIDENTIAL-DEBATES.rdata")

debates_2016_final<-data.table(debates_2016_final)


debates_2016_final[, year := str_extract(date,"[0-9]{4}")]

debates_2016_final<-debates_2016_final[year>=2015]



#lowercase all names
debates_2016_final[, speaker := tolower(speaker)]

#remove non-letter characters
debates_2016_final[, speaker := gsub("[^[:alnum:] ]", "", speaker)] 

##keep only trump / clinton responses
debates_2016_final<-debates_2016_final[grep("trump|clin",speaker)]

##remove HTML tags from content using this function
cleanfragment <- function(htmlString) {
htmlString <- gsub("<.*?>", "", htmlString) 
htmlString <- gsub("\\[.*]", "", htmlString) 
htmlString <- gsub("&.*;", "", htmlString)
return(htmlString) 

}

debates_2016_final[, fragment := cleanfragment(fragment)] 

##create a dummy variable indicating whether this was a primary or presidential debate
debates_2016_final[, primary := 0]
debates_2016_final[ grep("Candidates", debate), primary := 1]


#lets built a corpus object
DEBATES <- corpus(debates_2016_final$fragment) 
DEBATES[["speaker"]] <- debates_2016_final$speaker 
DEBATES[["debate"]] <- debates_2016_final$debate 
DEBATES[["date"]] <- debates_2016_final$date 
DEBATES[["primary"]] <- debates_2016_final$primary
```

```{r echo=FALSE, include=FALSE,results=''hide'}
clinton_1<-corpus_subset(DEBATES, speaker== "clinton" & primary == 1)
clinton_0<- corpus_subset(DEBATES, speaker == "clinton" & primary == 0)

summary(clinton_0)
```

#####3) Exploring text fragment with Heap's Law:
###### Combined Heaps Law:
```{r heaps_law, echo=FALSE, warning=FALSE, tidy=TRUE}

plot(log(DEBATES$Types), log(DEBATES$Tokens)) + abline(lm(log(DEBATES$Tokens) ~ log(DEBATES$Types)))

summary(lm(log(DEBATES$Tokens) ~log(DEBATES$Types)))
```

```{r speaker_df,echo=FALSE, warning=FALSE, tidy=TRUE}
#create trump only data frame
trump<-corpus_subset(DEBATES, speaker== "trump")
#create clinton only data frame
clinton<-corpus_subset(DEBATES, speaker== "clinton")
```
###### Clinton Heaps Law:
```{r clinton_heap,echo=FALSE, warning=FALSE, tidy=TRUE}
#add clinton heap from previous block
plot(log(clinton$Types), log(clinton$Tokens)) + abline(lm(log(clinton$Tokens) ~ log(clinton$Types)))

summary(lm(log(clinton$Tokens) ~log(clinton$Types)))
```
###### Trump Heaps Law:
```{r trump_heap, echo=FALSE, warning=FALSE, tidy=TRUE}
#add trump heap from previous block
plot(log(trump$Types), log(trump$Tokens)) + abline(lm(log(trump$Tokens) ~ log(trump$Types)))

summary(lm(log(trump$Tokens) ~log(trump$Types)))
```
#####4)Lexical Diversity Before and After Accepting Party's Nomination:



#####Clinton Heaps Law Before Party's Nomination:
```{r clinton_before_nom}
#Clinton Before Nominee
clinton_0<-corpus_subset(DEBATES, speaker== "clinton" & primary == 0)

#Graph
plot(log(clinton_0$Types), log(clinton_0$Tokens)) + abline(lm(log(clinton_0$Tokens) ~ log(clinton_0$Types)))
```
#####Clinton Heaps Law After Party's Nomination:
```{r clinton_after_nom}
#Clinton After Nominee
clinton_1<-corpus_subset(DEBATES, speaker== "clinton" & primary == 1)
clinton_1<- summary(clinton_1)

plot(log(clinton_1$Types), log(clinton_1$Tokens)) + abline(lm(log(clinton_1$Tokens) ~ log(clinton_1$Types)))
```

#####Trump Heaps Law Before Party's Nomination:
```{r trump_before_nom}
#Clinton After Nominee
trump_0<-corpus_subset(DEBATES, speaker== "trump" & primary == 0)
trump_0<- summary(trump_0)

plot(log(trump_0$Types), log(trump_0$Tokens)) + abline(lm(log(trump_0$Tokens) ~ log(trump_0$Types)))

summary(lm(log(trump_0$Types) ~log(trump_0$Tokens)))
```
#####Trump Heaps Law After Party's Nomination:
```{r trump_after_nom}
#Clinton After Nominee
trump_1<-corpus_subset(DEBATES, speaker== "trump" & primary == 1)
plot(log(trump_1$Types), log(trump_1$Tokens)) + abline(lm(log(trump_1$Tokens) ~ log(trump_1$Types)))
```


